name: .NET

on:
  push:
    branches: [ main, dev, feature/*, fix/*, release/* ]

  pull_request:
    branches: [ main ]

  release:
    types: [ published ]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

    # Create Local NuGet Source

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    # FlatArray

    - name: Restore FlatArray
      run: dotnet restore ./src/*/*/FlatArray.csproj

    - name: Build FlatArray
      run: dotnet build ./src/*/*/FlatArray.csproj --no-restore  -c Release

    - name: Pack FlatArray
      run: dotnet pack ./src/*/*/FlatArray.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore FlatArray.Tests
      run: dotnet restore ./src/*/*/FlatArray.Tests.csproj

    - name: Test FlatArray.Tests
      run: dotnet test ./src/*/*/FlatArray.Tests.csproj --no-restore  -c Release

    # FlatCollections

    - name: Restore FlatCollections
      run: dotnet restore ./src/*/*/FlatCollections.csproj

    - name: Build FlatCollections
      run: dotnet build ./src/*/*/FlatCollections.csproj --no-restore  -c Release

    - name: Pack FlatCollections
      run: dotnet pack ./src/*/*/FlatCollections.csproj --no-restore -o ~/nuget  -c Release

      # Push

    - name: Push Packages
      if: ${{ github.event_name == 'release' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetSourcePassword }} --skip-duplicate
